### ISSUE TITLE
Problems with interactive mode

### ISSUE THREAD

**Issue by JJetmar** [JJetmar/perfmon-grapher#5]
Sometimes this could happen:

Error: listen EACCES 0.0.0.0:65040
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at Application.listen (C:\Users\user\AppData\Roaming\nvm\v10.0.0\node_modules\@jjetmar\perfmon-grapher\node_modules\koa\lib\application.js:80:19)
    at C:\Users\user\AppData\Roaming\nvm\v10.0.0\node_modules\@jjetmar\perfmon-grapher\src\cli.js:58:21
    at process._tickCallback (internal/process/next_tick.js:178:7)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:174:19)

**Comment by JJetmar** [comment]
Temporary fix - run again with new generated port.
